esphome:
  name: curtain-living
  #includes:
  #  - curtain_switch.h


#switch:
#- platform: custom
#  lambda: |-
#    auto my_custom_switch = new MyCurtainSwitch();
#    App.register_component(my_custom_switch);
#    return {my_custom_switch};
#    name: "Curtain Living";
    
#  switches:
#    name: "Curtain Living"
    
binary_sensor:
  - platform: gpio
    name: "Pin GPIO17"
    pin: 10
    
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "b08779ffd3b6a8439241514d3b05849a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Curtain-Living"
    password: "qvQV6imLae9b"

captive_portal:
